server:
  port: ${ORDERSERVICE_PORT:8082}

spring:
  application:
    name: orderservice
  datasource:
    url: ${ORDERSERVICE_DB_URL:jdbc:postgresql://localhost:5432/orders_db}
    username: ${ORDERSERVICE_DB_USER:postgres}
    password: ${ORDERSERVICE_DB_PASS:postgresql}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: ${ORDERSERVICE_SHOW_SQL:false}
    hibernate:
      ddl-auto: ${ORDERSERVICE_DDL_AUTO:validate}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:https://discovery-service-a9bkgpgaf0hvb3d8.centralus-01.azurewebsites.net}
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
    hostname: orderservice