server:
  port: ${ORDERSERVICE_PORT:8082}

spring:
  application:
    name: orderservice
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: ${ORDERSERVICE_DB_USER:postgres}
    password: ${ORDERSERVICE_DB_PASS:postgresql}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: orderservice